#!/bin/bash

# date: 2018-08-29 - dott
# discription: Displays weather using accuweather

wget -q -O- http://www.accuweather.com/en/de/chemnitz/09111/current-weather/171238 | grep -A20 buttons.detail  | grep large | sed -e 's/<[^>]*>//g' | tr -s ' ' | cut -d ';' -f1 | grep -v '^$' | sed 's/&deg/°C /g' 
