#! /bin/bash
# quickly add notes to a file

notefile="/home/dott/docs/quicknotes.txt"
date="1"
dateformat="%d %b %Y - %H:%M"
if [ "$date" = "1" ]; then
	date +"$dateformat" >> $notefile
fi
echo "$@" >> $notefile
echo " " >> $notefile
