#!/bin/sh

# date: 2018-08-29 - dott
# records screen

if [ -z "$1" ]
then
        filename="$1.mp4"
else
filename="/tmp/screencast.mp4"
fi

ffmpeg -f x11grab -r 25 -s $(xrandr| grep '*' | tr -s " " | cut -d' ' -f2) -i :0.0 -c:v libx264 $filename
