#!/bin/bash

# Selection menu items goes here
if [ "$1" == 'caca' ]
then
	player='mpv -vo=caca'
elif [ "$1" == 'tct' ]
then
	player='mpv -vo=tct'
elif [ "$1" == '-p' ]
then
	player="$2"
else 
player=mpv
fi
SELECTION="ARD Tagesschau24 ARD_one ZDF ZDF_neo ZDFinfo ARTE Phoenix Bundestag_1 Bundestag_2 quit"

select options in $SELECTION; do

# here using the if statements you can perform the required  operation
if [ "$options" = "ARD" ]; then
    $player 'http://daserste_live-lh.akamaihd.net/i/daserste_de@91204/master.m3u8' -title ARD && exit

elif [ "$options" = "Tagesschau24" ]; then
	$player 'http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_3776_av-p.m3u8?sd=10&rebase=on' -title Tagesschau24 && exit

elif [ "$options" = "ARD_one" ]; then
	$player 'http://onelivestream-lh.akamaihd.net/i/one_livestream@568814/index_7_av-p.m3u8' -title ARD_one && exit

elif [ "$options" = "ZDF" ]; then
    $player 'https://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8' -title ZDF && exit

elif [ "$options" = "ZDF_neo" ]; then
    $player 'https://zdf1314-lh.akamaihd.net/i/de13_v1@392877/master.m3u8?' -title ZDF_neo && exit

elif [ "$options" = "ZDFinfo" ]; then
    $player 'https://zdf1112-lh.akamaihd.net/i/de12_v1@392882/master.m3u8?' -title ZDFinfo && exit

elif [ "$options" = "ARTE" ]; then
     $player 'http://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8' -title ARTE && exit

elif [ "$options" = "Phoenix" ]; then
    $player 'https://zdf0910-lh.akamaihd.net/i/de09_v1@392871/master.m3u8?' -title Phoenix && exit

elif [ "$options" = "Bundestag_1" ]; then
    $player 'https://c13014-l-hls.u.core.cdn.streamfarm.net/1000153copo/live/app144277506/BTTV_1/QdoHEQIoadKSHi6oKEp5ziZ2q/J7ekv9+hgpBxTSy2G2KefdbYTKWe5R2gMXKyP0.m3u8' -title Bundestag_1 && exit

elif [ "$options" = "Bundestag_2" ]; then
    $player 'https://c13014-l-hls.u.core.cdn.streamfarm.net/1000153copo/live/app144277506/BTTV_2/QdoHEQIoadKSHi6oKEp5ziZ2q/J7ekv9+hgpBxTSy2G2KefdbYTKWe5R2gMXKyP0.m3u8' -title Bundestag_2 && exit

elif [ "$options" = "quit" ]; then
        echo "You have selected $options"
    exit

# if something else is selected, show the menu again
else
    clear;
    echo "please select some options"

fi
done
