#!/bin/bash

# Selection menu items goes here
SELECTION="ARD Tagesschau24 ZDF ZDF_neo ZDFinfo ARTE Phoenix quit"

select options in $SELECTION; do

# here using the if statements you can perform the required  operation
if [ "$options" = "ARD" ]; then
    mpv 'http://live-ut-lh.daserste.de/i/daserste_ut_de@300832/index_1_av-b.m3u8?sd=10&rebase=on' -title ARD && exit

elif [ "$options" = "Tagesschau24" ]; then
	mpv 'http://tagesschau-lh.akamaihd.net/i/tagesschau_1@119231/index_3776_av-p.m3u8?sd=10&rebase=on' -title Tagesschau24 && exit

elif [ "$options" = "ZDF" ]; then
    mpv 'https://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8' -title ZDF && exit

elif [ "$options" = "ZDF_neo" ]; then
    mpv 'https://zdf1314-lh.akamaihd.net/i/de13_v1@392877/master.m3u8?' -title ZDF_neo && exit

elif [ "$options" = "ZDFinfo" ]; then
    mpv 'https://zdf1112-lh.akamaihd.net/i/de12_v1@392882/master.m3u8?' -title ZDFinfo && exit

elif [ "$options" = "ARTE" ]; then
     mpv 'http://artelive-lh.akamaihd.net/i/artelive_de@393591/master.m3u8' -title ARTE && exit

elif [ "$options" = "Phoenix" ]; then
    mpv 'https://zdf0910-lh.akamaihd.net/i/de09_v1@392871/master.m3u8?' -title Phoenix && exit

elif [ "$options" = "quit" ]; then
        echo "You have selected $options"
    exit

# if something else is selected, show the menu again
else
    clear;
    echo "please select some options"

fi
done
