#!/bin/bash

cd /tmp
link=$(wget -q -O- 'https://www.simmel.de/markt/gruena' | grep .pdf | cut -d '"' -f2)
filename=$(echo $link | cut -d'/' -f7)
wget "https://www.simmel.de/$link" -O $filename
mupdf $filename && rm $filename
